### ISSUE TITLE
wallet forgets address labels (android)

### ISSUE THREAD

**Issue by adrian-schnell** [DFXswiss/wallet#15]
#### What happened:
DFX LW forgets the set labels for addresses after restarting it.

#### What you expected to happen:
See the labels even after restarting the wallet

#### How to reproduce it (as minimally and precisely as possible):
- create > 2 addresses in the wallet
- tab on the top right button the show the overlay to switch the addresses
- click on "edit" and add custom labels for the addresses
- close the app & open again

**Comment by adrian-schnell** [comment]
can see this behaviour on Mac (m1, iOS version) as well

**Comment by ThaBrad** [comment]
Thanks so much @adrian-schnell , will look into it swiftly ;)!

**Comment by ThaBrad** [comment]
Sorry, but tried it a couple times on different devices and simulators, but NOT reproducible. Maybe you have a nieche device that specifically throws a bug with react-native?!

**Comment by ThaBrad** [comment]
If you want us to dig into further, please go into more detail.
