### ISSUE TITLE
wallet forgets addressbook entries (android)

### ISSUE THREAD

**Issue by adrian-schnell** [DFXswiss/wallet#16]
What happened:
DFX LW forgets the addresses created in the address book after restarting it.

What you expected to happen:
See the entries even after restarting the wallet

How to reproduce it (as minimally and precisely as possible):
- open the menu > address book
- add an address
- restart wallet

**Comment by adrian-schnell** [comment]
can see this behaviour on Mac (m1, iOS version) as well

**Comment by ThaBrad** [comment]
same as #15
