### ISSUE TITLE
Stock-Token LM-Pool Fehlermeldung bei Nachkauf des Tokens

### ISSUE THREAD

**Issue by Wendel-BS** [DFXswiss/wallet#31]
**Status:**
Über den Kaufen-Button in der App und über die Payment-Seite beim Erstellen von Kauf-Routen sind derzeit keine DUSD LM Pool Token auswählbar, da diese noch nicht zum Kauf über DFX freigegeben sind.

**Problem:**
Über die Token Zusatzoptionen in der App (Kaufen) kann man entsprechende DUSD LM Pool Token jedoch auswählen ...

![photo_2022-11-07_11-40-58](https://user-images.githubusercontent.com/117222124/200294734-b3e953d7-6190-46c9-9712-ce7eb18c11c5.jpg)

... und man erhält im weiteren Verlauf dann **folgende Fehlermeldung**:

![photo_2022-11-07_11-42-53](https://user-images.githubusercontent.com/117222124/200294522-fd5a7c3f-07a6-49cb-9295-46f2beb75a67.jpg)

**Quelle:**
[https://t.me/DFXswiss/82334](url)

**Vorschlag zur Abstellmaßnahme:**

1. Freigabe der DUSD LM Pool Token zum Kauf oder 
2. Deaktivierung der Kaufoption beim jeweiligen DUSD LM Pool Token in der App (bis Einführung von 1.).

**Comment by Kolibri1990** [comment]
Fixed :)
