### ISSUE TITLE
Aufruf der Payment-Seite aktuell "stark gewöhnungsbedürftig"

### ISSUE THREAD

**Issue by Wendel-BS** [DFXswiss/wallet#32]
**Status:** 
über den Button "Kaufen" und / oder "Verkaufen" finden Appnutzer nicht mehr - wie früher - die Payment-Seite, um somit gegebenenfalls angelegte Routen verwalten zu können.

**Problem:**
▪️  Anwender finden sich durch die letzten Updates in der DFX Smartphone App teilweise nicht mehr zurecht.
▪️  Die Weiterleitung über den Button "Staking" ist nicht wirklich intuitiv.

![photo_2022-11-08_19-05-00](https://user-images.githubusercontent.com/117222124/200641973-f6a57313-3480-4977-8a24-4dca953b016e.jpg)

**Quelle:**
https://t.me/DFXswiss/82396

**Vorschläge zu Abstellmaßnahmen:**

1. Neue zusätzliche, horizontale Schaltfläche (über oder unter) den Funktionsbuttons.
2. Beschriftung dieser neuen horizontalen Schaltfläche mit "zur Payment-Seite ..."

**Comment by Kolibri1990** [comment]
Gibt jetzt den MyDFX Button
