### ISSUE TITLE
Offramp "Bad request" - issue im Komfort-Modus

### ISSUE THREAD

**Issue by Wendel-BS** [DFXswiss/wallet#37]
**Status:**
Für den Verkauf von Krypto-Assets im Allgemeinen und für DFI im Speziellen stehen dem Nutzer der App folgende Modi zur Verfügung:
▫️ Komfort-Funktion
👉 über den Verkaufen-Button oben in der App oder aus dem entsprechenden Coin-Menue.

▫️  Expertenmodus
👉  über die Paymentseite in Verbindung Deposit-Adresse aus der Sell Route.

**Problem:**
Im Komfort-Modus hat ein Nutzer beim Versuch des Verkaufs von DFI eine "Bad request" Meldung erhalten und konnte den Verkauf nicht fortsetzen.

AEG-Methoden (Warm- und Kaltstart) waren nicht zielführend
Im Experten-Modus war der DFI-Verkauf problemfrei möglich.

**Screen-Shot:**
![photo_2022-12-15_16-43-42](https://user-images.githubusercontent.com/117222124/207914185-127c9b7b-1475-4824-8964-16dff371575b.jpg)

**Fehlerbericht des Nutzers:**

_Mobiles Endgerät: 
iPhone 13 Mini_ 

_Softwarestand:
iOS 16.1.1 (20B101)_

_Beschreibung:
Als erstes habe ich den coin dfi angeklickt dann auf „verkaufen“ dann im off-ramp Menü kam sofort der Fehler._ 

_Neustarten der App und des Gerätes brachten nix._ 

_Später habe ich es auch über den „Verkaufen“ Button im Hauptmenü probiert, dann dfi ausgewählt -> selber Fehler._ 

_Der Fehler kommt egal welchen coin ich versuche._ 

_Auszahlen über manuelles versenden an off-ramp Adresse funktioniert fehlerfrei._ 

_Hoffe das kann gelöst werden, der Verkaufenbutton ist schon die besser user exp :)_

**Quelle:**

https://t.me/DFXswiss/85499

**Erwartungshaltung:**

- Ermittlung der Grundursache
- Implementierung einer langfristigen Abstellmaßnahme
- Folglich: eine Problemlösung

**Comment by Kolibri1990** [comment]
Handynummer hatte gefehlt. Fehlermeldung ist korrekt.
