### ISSUE TITLE
Error Code 1 when trying to convert DFI to UXTO

### ISSUE THREAD

**Issue by HelloLudger** [DFXswiss/wallet#4]
#### What happened:
I have for some reasons 0 UXTO so I tried to change some DFI to UXTO. It failed because I don't have enough UXTO to pay the exchange.  

![20220405_144422.jpg](https://user-images.githubusercontent.com/861649/161756614-6a44c3eb-ac6a-4e49-a142-4c7a88cbace0.jpg)

#### What you expected to happen:
I expected the change to happen. 

#### How to reproduce it (as minimally and precisely as possible):
Probably any account without any UXTO. 

#### Anything else we need to know?:
Doesn't seem possible to send UXTO fro. Another account.

**Comment by PhoenixKuzia** [comment]
Hey HelloLudger,
You need some UTXO to convert Token to UTXO :D
you can get some for free at https://utxo.mydefichain.com/

for faster support feel free to join our Telegram group:
https://t.me/DFXswiss_en

best regards
Pho
