### ISSUE TITLE
DFX BTC Einzahladresse erstellen (Zusatzinfo erforderlich)

### ISSUE THREAD

**Issue by Wendel-BS** [DFXswiss/wallet#65]
**Status:**
Beim Generieren der DFX BTC Einzahladresse wird die Info angezeigt, dass hierfür der KYC-Prozess erforderlich ist.

**Problem:**
Selbst bei „KYC-Status: Verifizierung abgeschlossen“ auf der Paymentseite des Nutzers, muss noch eine weitere Bedinung erfüllt sein, denn der Nutzer benötigt noch einen RefCode (= eine Ein- oder Auszahlung), um sein Bankonto zu verifizieren.
Diese Info fehlt derzeit noch in der App (siehe Info-Box unten im Screen-Shot)

**Änderungsantrag:**
Text in der Info-Box mit den Bedingungen zum Erstellen der DFX BTC Einzahladresse vervollständigen.
Hinzufügen der Info bzgl. dem RefCode.
(= mind. eine Ein- oder Auszahlung)

**Screenshots :**

![BTC-Einzahladresse anlegen](https://user-images.githubusercontent.com/117222124/226118484-a7245656-8b43-4639-aca4-3e1dbc8596dd.jpg)

Der komplettierte KYC-Status alleine (auf der Paymentseite des Nutzers) reicht nicht aus.
![KYC-Status](https://user-images.githubusercontent.com/117222124/226118533-9bf75fcc-9440-441c-a727-d0e989aa0020.jpeg)

**Kommentar:**
_Da der KYC Process alleine ja nicht ausreicht, um an die BTC Adresse zu gelangen, würde ich den Hinweis oben (im Screen-Shot) abändern. 
Von einer benötigten Ein- oder Auszahlung auf sein Bankkonto (RefCode) ist keine Rede. 
Das hat bei mir viele Fragen ausgelöst._

**Quelle:**

https://t.me/DFXswiss/92137

**Erwartungshaltung:**
▫️ Nutzererlebnis verbessern
▫️ Schaffen eines Mehrwerts
▫️ Optimierung (Verbesserung) der App

**Comment by Kolibri1990** [comment]
Erledigt.
